ktor:
    application:
        modules:
            - me.mintdev.ApplicationKt.module
    deployment:
        port: 8080
        auto-reload: true
jwt:
    issuer: "http://localhost"
    audience: "mintdev-audience"
    realm: "mintdev ktor sample app"
    secret: "secret" #${SECRET}
